package com.novascanner.network.localization

object Strings {
    var isRtl = false
    var isDark = true

    private val en = mapOf(
        "app_name" to "Nova Radar",
        "tab_radar" to "Radar",
        "tab_import" to "Import",
        "tab_installer" to "Installer",
        "tab_settings" to "Settings",
        "tab_about" to "About",
        "start_scan" to "Start Scan",
        "stop_scan" to "Stop",
        "scanning" to "Scanning...",
        "ips_found" to "IPs Found",
        "manual_ip" to "Manual IP",
        "cidr_scan" to "CIDR Scan",
        "enter_ips" to "Enter IPs (one per line)",
        "enter_cidr" to "CIDR range (e.g. 104.16.0.0/12)",
        "port" to "Port",
        "no_results" to "No results. Start a scan!",
        "copy" to "Copy",
        "copy_all" to "Copy All",
        "copy_top10" to "Top 10",
        "pack_greens" to "Pack Greens",
        "export_txt" to "Export TXT",
        "suffix_on" to "Suffix: ON",
        "suffix_off" to "Suffix: OFF",
        "suffix" to "Nova Proxy Suffix",
        "suffix_hint" to "e.g. ?ed=2560",
        "threads" to "Threads",
        "timeout" to "Timeout (ms)",
        "sni" to "SNI Hostname",
        "lang" to "Language",
        "about" to "About",
        "version" to "Version",
        "grade" to "Grade",
        "latency" to "Latency",
        "colo" to "Colo",
        "working" to "Working",
        "failed" to "Failed",
        "clear" to "Clear",
        "save_success" to "Saved to Downloads",
        "app_desc" to "Nova Radar - Advanced CDN IP Scanner",
        "build_info" to "v1.1.0 | Kotlin + Jetpack Compose",
        "worker_title" to "Nova Proxy Worker",
        "worker_api" to "Cloudflare API Token",
        "worker_name" to "Worker Name",
        "worker_uuid" to "UUID",
        "worker_ip" to "Proxy IP",
        "worker_deploy" to "Deploy Worker",
        "worker_demo" to "Demo Mode",
        "worker_status" to "Status",
        "worker_url" to "Worker URL",
        "worker_success" to "Deployed Successfully!",
        "learn_more" to "Learn More",
        "source_code" to "Source Code",
        "filter" to "Filter by grade",
        "history" to "Scan History",
        "clear_history" to "Clear History",
        "elapsed" to "Elapsed",
        "no_history" to "No scans yet",
        "retry" to "Retry Count",
        "retry_hint" to "Number of retries on failure",
        "delay" to "Delay (ms)",
        "delay_hint" to "Delay between probes",
        "ping_only" to "Ping Only (TCP)",
        "ping_only_hint" to "Skip TLS/HTTP, just TCP",
        "auto_save" to "Auto-save results",
        "auto_save_hint" to "Save results to file after scan",
        "theme" to "Dark theme",
        "results_saved" to "Results auto-saved",
        "scan_complete" to "Scan Complete!",
        "working_count" to "working IPs found"
    )

    private val fa = mapOf(
        "app_name" to "نوا رادار",
        "tab_radar" to "رادار",
        "tab_import" to "ورود",
        "tab_installer" to "نصب",
        "tab_settings" to "تنظیمات",
        "tab_about" to "درباره",
        "start_scan" to "شروع اسکن",
        "stop_scan" to "توقف",
        "scanning" to "در حال اسکن...",
        "ips_found" to "آی‌پی پیدا شد",
        "manual_ip" to "آی‌پی دستی",
        "cidr_scan" to "اسکن CIDR",
        "enter_ips" to "آی‌پی‌ها را وارد کن (یکی در هر خط)",
        "enter_cidr" to "محدوده CIDR (مثلاً 104.16.0.0/12)",
        "port" to "پورت",
        "no_results" to "نتیجه‌ای نیست. یک اسکن شروع کن!",
        "copy" to "کپی",
        "copy_all" to "همه",
        "copy_top10" to "۱۰ تای برتر",
        "pack_greens" to "سبزها",
        "export_txt" to "خروجی TXT",
        "suffix_on" to "پسوند: فعال",
        "suffix_off" to "پسوند: غیرفعال",
        "suffix" to "پسوند نوا پروکسی",
        "suffix_hint" to "مثلاً ?ed=2560",
        "threads" to "تعداد رشته",
        "timeout" to "مهلت (ms)",
        "sni" to "میزبان SNI",
        "lang" to "زبان",
        "about" to "درباره",
        "version" to "نسخه",
        "grade" to "گرید",
        "latency" to "تأخیر",
        "colo" to "موقعیت",
        "working" to "موفق",
        "failed" to "ناموفق",
        "clear" to "پاک کردن",
        "save_success" to "ذخیره شد",
        "app_desc" to "نوا رادار - اسکنر پیشرفته آی‌پی",
        "build_info" to "v1.1.0 | Kotlin + Jetpack Compose",
        "worker_title" to "نوا پروکسی",
        "worker_api" to "توکن Cloudflare",
        "worker_name" to "اسم ورکر",
        "worker_uuid" to "UUID",
        "worker_ip" to "آی‌پی پروکسی",
        "worker_deploy" to "اجرای ورکر",
        "worker_demo" to "حالت نمایشی",
        "worker_status" to "وضعیت",
        "worker_url" to "آدرس ورکر",
        "worker_success" to "با موفقیت اجرا شد!",
        "learn_more" to "بیشتر بدانید",
        "source_code" to "سورس کد",
        "filter" to "فیلتر بر اساس گرید",
        "history" to "تاریخچه اسکن",
        "clear_history" to "پاک کردن تاریخچه",
        "elapsed" to "زمان سپری شده",
        "no_history" to "هنوز اسکنی انجام نشده",
        "retry" to "تعداد تلاش مجدد",
        "retry_hint" to "تعداد دفعات تکرار در صورت خطا",
        "delay" to "تأخیر (ms)",
        "delay_hint" to "تأخیر بین پروب‌ها",
        "ping_only" to "فقط پینگ (TCP)",
        "ping_only_hint" to "بدون TLS/HTTP، فقط TCP",
        "auto_save" to "ذخیره خودکار نتایج",
        "auto_save_hint" to "ذخیره نتایج در فایل پس از اسکن",
        "theme" to "پوسته تیره",
        "results_saved" to "نتایج خودکار ذخیره شد",
        "scan_complete" to "اسکن کامل شد!",
        "working_count" to "آی‌پی فعال پیدا شد"
    )

    fun get(key: String): String = (if (isRtl) fa else en)[key] ?: en[key] ?: key
}
