package com.novascanner.network.localization

object Strings {
    var isRtl = false

    private val en = mapOf(
        "app_name" to "Nova Radar",
        "scan" to "Scan",
        "results" to "Results",
        "settings" to "Settings",
        "start_scan" to "Start Scan",
        "stop_scan" to "Stop Scan",
        "scanning" to "Scanning...",
        "ips_found" to "IPs Found",
        "ip_input" to "IP Input",
        "manual_ip" to "Manual IP",
        "cidr_range" to "CIDR Range",
        "enter_ips" to "Enter IPs (one per line or comma-separated)",
        "enter_cidr" to "Enter CIDR (e.g. 104.16.0.0/12)",
        "scan_count" to "Number of IPs to scan",
        "no_results" to "No results yet. Start a scan!",
        "copy" to "Copy",
        "copied" to "Copied!",
        "export_txt" to "Export as TXT",
        "copy_all" to "Copy All",
        "copy_top10" to "Copy Top 10",
        "pack_greens" to "Pack Green IPs",
        "suffix_enabled" to "Suffix: ON",
        "suffix_disabled" to "Suffix: OFF",
        "suffix_text" to "Nova Proxy Suffix",
        "suffix_hint" to "e.g. ?ed=2560 or /ws/path",
        "threads" to "Concurrent Threads",
        "timeout" to "Timeout (ms)",
        "sni_host" to "SNI Hostname",
        "language" to "Language",
        "about" to "About",
        "version" to "Version",
        "latency" to "Latency",
        "grade" to "Grade",
        "port" to "Port",
        "colo" to "Colo",
        "status_working" to "Working",
        "status_failed" to "Failed",
        "select_output" to "Select Output Format",
        "with_suffix" to "With Suffix",
        "without_suffix" to "Without Suffix",
        "clear_results" to "Clear Results",
        "confirm_clear" to "Clear all results?",
        "yes" to "Yes",
        "no" to "No",
        "save_success" to "Saved to Downloads folder",
        "app_desc" to "Nova Radar - Advanced Network Scanner\nClean IP detection for CDN networks",
        "build_info" to "Kotlin + Jetpack Compose",
    )

    private val fa = mapOf(
        "app_name" to "نوا رادار",
        "scan" to "اسکن",
        "results" to "نتایج",
        "settings" to "تنظیمات",
        "start_scan" to "شروع اسکن",
        "stop_scan" to "توقف اسکن",
        "scanning" to "در حال اسکن...",
        "ips_found" to "آی‌پی‌های پیدا شده",
        "ip_input" to "ورودی آی‌پی",
        "manual_ip" to "آی‌پی دستی",
        "cidr_range" to "محدوده CIDR",
        "enter_ips" to "آی‌پی‌ها را وارد کنید (هر خط یک آی‌پی)",
        "enter_cidr" to "CIDR را وارد کنید (مثلاً 104.16.0.0/12)",
        "scan_count" to "تعداد آی‌پی برای اسکن",
        "no_results" to "هنوز نتیجه‌ای وجود ندارد. اسکن را شروع کنید!",
        "copy" to "کپی",
        "copied" to "کپی شد!",
        "export_txt" to "خروجی TXT",
        "copy_all" to "کپی همه",
        "copy_top10" to "کپی ۱۰ تای برتر",
        "pack_greens" to "بسته‌بندی آی‌پی‌های سبز",
        "suffix_enabled" to "سافیکس: روشن",
        "suffix_disabled" to "سافیکس: خاموش",
        "suffix_text" to "سافیکس نوا پروکسی",
        "suffix_hint" to "مثلاً ?ed=2560 یا /ws/path",
        "threads" to "تعداد نخ‌های همزمان",
        "timeout" to "مهلت (میلی‌ثانیه)",
        "sni_host" to "نام میزبان SNI",
        "language" to "زبان",
        "about" to "درباره",
        "version" to "نسخه",
        "latency" to "تأخیر",
        "grade" to "درجه",
        "port" to "پورت",
        "colo" to "سرور",
        "status_working" to "فعال",
        "status_failed" to "ناموفق",
        "select_output" to "انتخاب فرمت خروجی",
        "with_suffix" to "با سافیکس",
        "without_suffix" to "بدون سافیکس",
        "clear_results" to "پاک کردن نتایج",
        "confirm_clear" to "همه نتایج پاک شود؟",
        "yes" to "بله",
        "no" to "خیر",
        "save_success" to "در پوشه Downloads ذخیره شد",
        "app_desc" to "نوا رادار - اسکنر پیشرفته شبکه\nتشخیص آی‌پی تمیز برای شبکه‌های CDN",
        "build_info" to "Kotlin + Jetpack Compose",
    )

    fun get(key: String): String {
        val map = if (isRtl) fa else en
        return map[key] ?: en[key] ?: key
    }
}
